### ISSUE TITLE
Flatpak not starting due to local Python module error (cairo)

### ISSUE THREAD

**Issue by RedBearAK** [pdfarranger/pdfarranger#1025]
The Flatpak app is not starting for me on Fedora 39 (GNOME), so I tried it in a terminal and it seems to be trying to use a locally installed Python module from my home folder, and running into an error: 

```sh
flatpak run com.github.jeromerobert.pdfarranger 
Traceback (most recent call last):
  File "/app/bin/pdfarranger", line 5, in <module>
    from pdfarranger.pdfarranger import main
  File "/app/lib/python3.11/site-packages/pdfarranger/pdfarranger.py", line 144, in <module>
    from . import pageutils
  File "/app/lib/python3.11/site-packages/pdfarranger/pageutils.py", line 19, in <module>
    import cairo
  File "/home/kris/.local/lib/python3.11/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/kris/.local/lib/python3.11/site-packages/cairo/_cairo.cpython-311-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index
```

I feel like this shouldn't even be attempting to use anything in ~/.local/lib/. Shouldn't it be looking for this Python package in its own /app/lib folder? 

I tried renaming the ~/.local/lib/python3.11 folder and now the app starts up. But I have a lot of packages in there so I need to move it back to the original name. 

System and Versions
-------------------

-   PDF Arranger version and where you get it (distro package, flatpak, pip, git, download, ...)

Flatpak from Flathub, it just updated itself a few minutes ago before I tried to start it again. (But the problem was happening before that update.)

-   pikepdf version and where you get it (distro package, pip, git, ...)

No idea what this is referring to. I assume this is embedded in the Flatpak. 

-   OS name and version (e.g.: Windows 10, Fedora 33, ...)

Fedora 39 Workstation (GNOME 45)

**Comment by dreua** [comment]
Looks like yet another stupid flatpak-ecosystem bug to me:
```
[da@David-UB ~]$ flatpak run --command=bash com.github.jeromerobert.pdfarranger 
bash: /usr/share/git-core/contrib/completion/git-prompt.sh: No such file or directory
[da@David-UB ~]$ python -m site
sys.path = [
    '/home/da',
    '/usr/lib/python311.zip',
    '/usr/lib/python3.11',
    '/usr/lib/python3.11/lib-dynload',
    '/home/da/.local/lib/python3.11/site-packages',
    '/app/lib/python3.11/site-packages',
    '/usr/lib/python3.11/site-packages',
]
USER_BASE: '/home/da/.local' (exists)
USER_SITE: '/home/da/.local/lib/python3.11/site-packages' (exists)
ENABLE_USER_SITE: True
```
(Note that the second command is run in the flatpak's context but the prompt does not indicate that.)

**Comment by dreua** [comment]
Could you try running it like this and report if that helps?
```
flatpak run --nofilesystem=~/.local/lib/ com.github.jeromerobert.pdfarranger
```

**Comment by dreua** [comment]
Due to your bug report here which lead to my issue against the documtation, @bbhtt is just fixing this regression in the Gnome flatpak platform, thanks everyone! 🤝

**Comment by RedBearAK** [comment]
@dreua 

> fixing this regression in the Gnome flatpak platform

That does seem like a necessary place to have a fix for this. 👍🏽 

> Could you try running it like this and report if that helps?

Yes, that added `nofilesystem` to block the usage of ~/.local/lib allows it to start up. 👍🏽 

However, I have had occasion to need to manipulate `sys.path` in a couple of my own Python scripts to make sure they didn't attempt to use local packages over the standard or `venv` versions the script needed. Perhaps your app should also attempt to filter out such locations from the `sys.path` it is given by the Flatpak environment. Just to be on the safe side. 

Thanks for the quick response.

**Comment by dreua** [comment]
> However, I have had occasion to need to manipulate `sys.path` in a couple of my own Python scripts to make sure they didn't attempt to use local packages over the standard or `venv` versions the script needed. Perhaps your app should also attempt to filter out such locations from the `sys.path` it is given by the Flatpak environment. Just to be on the safe side.

I'm not entirely sure I understand what you mean here: For flatpaks the fix in Gnome platform should disable the local packages altogether, then we should be fine. For regular linux packages I hope that the package has proper dependencies and I would assume that Python would give priority to system installed package before looking into the user home directory. (At least I've never heard of issues here.)
If someone installs it via pip or in a venv they probably know what they're doing and taking the pikepdf from there might as well be expected and wanted behavior. (I myself did use this to check another bug against different pikepdf versions, quite handy!)

Any further manipulation of the package discovery logic on application side therefore seems like a bad idea to me at the moment.

**Comment by RedBearAK** [comment]
> I'm not entirely sure I understand what you mean here: For flatpaks the fix in Gnome platform should disable the local packages altogether, then we should be fine. 

Yes, you should be, but how long will they take to fix that, and is it guaranteed not to get messed up again somehow in the future? You would think this would have been fixed years ago. 

> For regular linux packages I hope that the package has proper dependencies and I would assume that Python would give priority to system installed package before looking into the user home directory.

Wouldn't that make it difficult to use a local package without deliberately changing the path so that an app run by the user would look into the local library first? 

All I know is, I had to fix a problem similar to this in the past with a Python installer script, though it might have been more about the `PATH` variable,  and filtering `sys.path` was only about escaping from a pre-existing `venv` setup someone put in their shell's RC file. 

If you think it's not necessary to double-check the `PATH` or `sys.path` that your app uses, for these kinds of issues, you may be correct. I still don't have that much experience with this sort of thing, leading to putting backup fixes in place that may be considered excessive by some standards.

**Comment by dreua** [comment]
I got the import precedence wrong, the user directory is actually preferred, at least on my machine. I think I understand your point now, still not sure if we should try to change that on application level. (Unless there is an actual use case which we haven't had until now.)

> but how long will they take to fix that

Soon, I hope: The PR is already there, I'm monitoring that and will check when that will be released once merged. If that turns out to take longer we can implement a workaround, of course.

I'm against implementing preemptive workarounds for stuff that only broke once. If we start doing that, we will and up shipping laptops with PDF Arranger preinstalled. And maybe include some solar panels for cases where the grid is unavailable :wink:

**Comment by RedBearAK** [comment]
> I got the import precedence wrong, the user directory is actually preferred, at least on my machine. I think I understand your point now

Oh, good, I thought I was losing it for a second there. 😄 

> PDF Arranger preinstalled. And maybe include some solar panels

Don't knock the dream. Just let it happen. ☁️ 🌥️ 🌤️ 🌞

**Comment by dreua** [comment]
> It should be released already. You just need to download the update (flatpak update or via a GUI) to get it.

@RedBearAK  Could you check if it is fixed already?

**Comment by RedBearAK** [comment]
@dreua 

> Could you check if it is fixed already?

I was going to do a before/after check, but it looks like I can't replicate the problem this morning, even though that `cairo` local package location still shows up in `sys.path` for some reason, and I couldn't find any permanent setting modification in Flatseal, but the app is starting without errors. 

```sh
flatpak run --command=bash com.github.jeromerobert.pdfarranger

python -m site
sys.path = [
    '/home/kris/.local/lib/python3.11/site-packages/cairo',
    '/usr/lib/python311.zip',
    '/usr/lib/python3.11',
    '/usr/lib/python3.11/lib-dynload',
    '/app/lib/python3.11/site-packages',
    '/usr/lib/python3.11/site-packages',
]
USER_BASE: '/var/data/python' (doesn't exist)
USER_SITE: '/var/data/python/lib/python3.11/site-packages' (doesn't exist)
ENABLE_USER_SITE: True
```

Maybe because the updated supporting Flatpak was already pulled down automatically yesterday? 

```sh
Jan  4 06:59:15 deploy update  org.gnome.Platform.Compat.i386                      45           system       flathub
Jan  4 06:59:16 deploy update  org.gnome.Platform.Locale                           45           system       flathub
...
Jan  4 07:05:47 deploy update  org.gnome.Platform                                  45           system       flathub
```

I have several other updates that were automatically applied early this morning, but none seem directly relevant unless the fix goes beyond the GNOME stuff and has something to do with these: 

```sh
Jan  5 06:59:43 deploy update  org.freedesktop.Platform.Compat.i386                23.08        system       flathub
Jan  5 07:01:23 deploy update  org.freedesktop.Platform.GL.default                 23.08        system       flathub
Jan  5 07:02:06 deploy update  org.freedesktop.Platform.GL.default                 23.08-extra  system       flathub
Jan  5 07:02:54 deploy update  org.freedesktop.Platform.GL32.default               23.08        system       flathub
Jan  5 07:03:14 deploy update  org.freedesktop.Platform.GL32.default               23.08-extra  system       flathub
Jan  5 07:03:16 deploy update  org.freedesktop.Platform.Locale                     23.08        system       flathub
Jan  5 07:03:18 deploy update  org.freedesktop.Platform.ffmpeg-full                23.08        system       flathub
Jan  5 07:03:21 deploy update  org.freedesktop.Platform.ffmpeg_full.i386           23.08        system       flathub
Jan  5 07:03:27 deploy update  org.freedesktop.Sdk.Locale                          23.08        system       flathub
...
Jan  5 07:10:05 deploy update  org.freedesktop.Sdk                                 23.08        system       flathub
Jan  5 07:10:10 deploy update  org.freedesktop.Platform                            23.08        system       flathub
```

Doesn't seem to be a problem anymore. 

Really odd that one particular local Python package is ending up in `sys.path`, not the whole `site-packages`. Wish I understood why that was happening. 

Oh, I exited my terminal and opened a new one, and it disappeared. Or at least it changed to just my home folder. Which still seems kind of unnecessary? 

```sh
flatpak run --command=bash com.github.jeromerobert.pdfarranger

python -m site
sys.path = [
    '/home/kris',
    '/usr/lib/python311.zip',
    '/usr/lib/python3.11',
    '/usr/lib/python3.11/lib-dynload',
    '/app/lib/python3.11/site-packages',
    '/usr/lib/python3.11/site-packages',
]
USER_BASE: '/var/data/python' (doesn't exist)
USER_SITE: '/var/data/python/lib/python3.11/site-packages' (doesn't exist)
ENABLE_USER_SITE: True
```

So strange. But the app was failing to start when launched with Ulauncher, not just from the terminal command. So it can't have been just something odd happening in a single terminal session. 

Anyway, you can probably close this as resolved.

**Comment by dreua** [comment]
> Maybe because the updated supporting Flatpak was already pulled down automatically yesterday?

That could very well be the case. I'm pretty sure it is in org.gnome.Platform.

> Really odd that one particular local Python package is ending up in `sys.path`, not the whole `site-packages`. Wish I understood why that was happening.
> 
> Oh, I exited my terminal and opened a new one, and it disappeared. Or at least it changed to just my home folder. Which still seems kind of unnecessary?

I think I read that in the documentation: The current working directory is always added to the path. Somewhat unexpected, I agree. If there is a reliable, ideally "best practice" way to filter that we might consider it but changing that only in PDF Arranger without there being a real issue with it is not the way to go imo.

Thanks for the help, glad we got this fixed upstream so fast!
