### ISSUE TITLE
Source build on Linux (ubuntu 18.04) doesn't work when desktop folder of PDFarranger is removed

### ISSUE THREAD

**Issue by Just-Another-Gnumer** [pdfarranger/pdfarranger#428]
When the source folder of PDFarrranger 1.70 is on the desktop it launches but has [this error](https://github.com/pdfarranger/pdfarranger/issues/427)

If I move the source folder to the trashbin it will not launch and I get this error
```
USERNAME@Bionic3883:~$ /home/USERNAME/.local/bin/pdfarranger
Traceback (most recent call last):
  File "/home/USERNAME/.local/bin/pdfarranger", line 33, in <module>
    sys.exit(load_entry_point('pdfarranger', 'console_scripts', 'pdfarranger')())
  File "/home/USERNAME/.local/bin/pdfarranger", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/home/USERNAME/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 604, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/USERNAME/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 229, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for pdfarranger
```

**Comment by jeromerobert** [comment]
Your `~/.local/bin/pdfarranger` is very different from mine. Could you paste it ? Could you also give your version of  `setuptools` with `python3 -c "import setuptools; print(setuptools.__version__)"`.

What happen if you run `python3 -m pdfarranger` (from any folder) instead of `~/.local/bin/pdfarranger` ?

**Comment by Just-Another-Gnumer** [comment]
1. `bash: /.local/bin/pdfarranger: No such file or directory`
(this might be the problem)

2. Setup Tools: 52.0.0

3. /usr/bin/python3: No module named pdfarranger

**Comment by jeromerobert** [comment]
> bash: /.local/bin/pdfarranger: No such file or directory

This is not possible, the stack in your first message says you have it.

**Comment by jeromerobert** [comment]
You forgot the `~`.

**Comment by Just-Another-Gnumer** [comment]
This is what I found  on the search. I did not find that folder.

![image](https://user-images.githubusercontent.com/78667207/109401361-25931580-7946-11eb-850c-9ee4ace29ad6.png)

**Comment by Just-Another-Gnumer** [comment]
No I did not find anything.

**Comment by Just-Another-Gnumer** [comment]
Sorry about the confusion. 

Early I tried to solve the problem by manually moving the files into '/.local/lib/python3.6/site-packages/importlib_metadata'

How do I install pdfarranger correctly? I will rerun these commands.

`git clone https://github.com/pdfarranger/pdfarranger.git
cd pdfarranger
pip install -e .
./setup.py build
python3 -m pdfarranger
```

**Comment by Just-Another-Gnumer** [comment]
I got the file in the correct directory by reinstalling I still have the same problem.
When typing in PDFarranger, I get this error
`
USERNAME@Bionic3883:~/.local/bin$ pdfarranger
Traceback (most recent call last):                                                                                       
  File "/home/USERNAME/.local/bin/pdfarranger", line 33, in <module>                                                     
    sys.exit(load_entry_point('pdfarranger', 'console_scripts', 'pdfarranger')())                                                  
  File "/home/USERNAME/.local/bin/pdfarranger", line 22, in importlib_load_entry_point                                             
    for entry_point in distribution(dist_name).entry_points                                                                                    
  File "/home/USERNAME/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 604, in distribution                           
    return Distribution.from_name(distribution_name)
  File "/home/USERNAME/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 229, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for pdfarranger
`

`contrast@Bionic3883:~$ whereis pdfarranger
pdfarranger: /home/USERNAME/.local/bin/pdfarranger`

**Comment by Just-Another-Gnumer** [comment]
This problem has been resolved the best way I know how.

I made a bashscript   `cd /home/USERNAME/Applications/pdfarranger && python3 -m pdfarranger` added it to my start menu by getting data from xprop and adding a desktop file to /home/USERNAME/.local/share/applications/

**Comment by jeromerobert** [comment]
For the records...

This bug is not fixed. We still don't know why, in that case the generated `bin/pdfarranger` script is buggy. We still don't know how it looks like. This is more likely not a bug in pdfarranger but an incompatibility between python, pkg_resources and/or setuptools. Hopefuly one day someone will be able to reproduce it.
